version: 0.0
os: linux
files:
  - source: htdocs/
    destination: /home/www-virtual/www.blog-test.jp/htdocs
hooks:
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
